MPMG-Web/src/main/java/fr/eql/ai110/mpmg/controller/LoginManagedBean.java
package fr.eql.ai110.mpmg.controller;

import java.io.Serializable;

import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpSession;

import fr.eql.ai110.mpmg.entity.User;
import fr.eql.ai110.mpmg.ibusiness.AccountIBusiness;

@ManagedBean(name="mbLogin")
@SessionScoped
public class LoginManagedBean implements Serializable{

	private static final long serialVersionUID = 1L;
	
	private String login;
	private String password;
	private String name;
	private String surname;
	private String email;
	private User user;
	
	@EJB
	private AccountIBusiness accountBusiness;
	
	public String create() {
		String forward = "";
		User user = new User();
		user.setLogin(login);
		user.setName(name);
		user.setSurname(surname);
		user.setEmail(email);
		user.setIsMember(true);
		user.setIsSubscriber(false);
		user.setIsAdmin(false);
		
		if(emailIsValid(email)) {
			accountBusiness.create(user, password);
			forward = "/index.xhtml?faces-redirection=true";
		} else {
			FacesMessage efacesMessage = new FacesMessage(FacesMessage.SEVERITY_WARN, "Email incorrect", "Email incorrect");
			FacesContext.getCurrentInstance().addMessage("loginForm:inpEmail", efacesMessage);
			user = null;
			forward = "/create.xhtml?faces-redirection=false";
		}
		return forward;
	}
	
	public String connect() {
		String forward = null;
		user = accountBusiness.connect(login, password);
		if(user != null) {
			FacesContext facesContext = FacesContext.getCurrentInstance();
			HttpSession session = (HttpSession) facesContext.getExternalContext().getSession(false);
			session.setAttribute("connectedUser", user);
			forward = "/index.xhtml?faces-redirection=true";
		}else {
			FacesMessage facesMessage = new FacesMessage(
					FacesMessage.SEVERITY_WARN,
					"Identifiant et/ou mot de passe incorrect(s)",
					"Identifiant et/ou mot de passe incorrect(s)"
					);
			FacesContext.getCurrentInstance().addMessage("loginForm:inpLogin", facesMessage);
			FacesContext.getCurrentInstance().addMessage("loginForm:inpPassword", facesMessage);
			forward = "/login.xhtml?faces-redirection=false";
		}
		return forward;
	}
	
	public boolean isConnected() {
		FacesContext facesContext = FacesContext.getCurrentInstance();
		HttpSession session = (HttpSession) facesContext.getExternalContext().getSession(false);
		user = (User) session.getAttribute("connectedUser");
		return user != null;
	}
	public boolean hasAccount() {
		FacesContext facesContext = FacesContext.getCurrentInstance();
		HttpSession session = (HttpSession) facesContext.getExternalContext().getSession(false);
		user = (User) session.getAttribute("connectedUser");
		return user != null;
	}
	
	public String disconnect() {
		HttpSession session = (HttpSession) FacesContext.getCurrentInstance()
							.getExternalContext().getSession(true);
		session.invalidate();
		user = null;
		return "/login.xhtml?faces-redirection=true";
	}
	
	private boolean emailIsValid(String email) {
		
		boolean emailIsValid = false;
		int upperCount = 0;
		
		for (int i = 0; i < email.length(); i++) {
			char ch = email.charAt(i);
			if(Character.isUpperCase(ch))
				upperCount++;
		}
		if(email.contains("@") && upperCount > 0) {
			emailIsValid = true;
		} else {
			emailIsValid = false;
		}
			
		return emailIsValid;
	}
	public void  update() {
		user = accountBusiness.update(user);
	}

	public String getLogin() {
		return login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSurname() {
		return surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}
	

}

MPMG-Web/src/main/java/fr/eql/ai110/mpmg/controller/RecipeManagedBean.java
package fr.eql.ai110.mpmg.controller;

import java.io.Serializable;
import java.lang.reflect.Type;
import java.util.List;
import java.util.Set;


import javax.ejb.EJB;
import javax.enterprise.inject.spi.Bean;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpSession;

import fr.eql.ai110.mpmg.entity.FavoriteRecipe;
import fr.eql.ai110.mpmg.entity.Recipe;
import fr.eql.ai110.mpmg.entity.User;
import fr.eql.ai110.mpmg.ibusiness.FavoriteRecipeIBusiness;
import fr.eql.ai110.mpmg.ibusiness.RecipeIBusiness;

@ManagedBean(name="mbRecipe")
@SessionScoped
public class RecipeManagedBean implements Serializable {

	private static final long serialVersionUID = 1L;


	private User connectedUser;
	private Set<Recipe> connectedUserRecipes;
	private Recipe recipe;
	private FavoriteRecipe favRecipe;

	@EJB
	private RecipeIBusiness recipeBusiness;
	@EJB
	private FavoriteRecipeIBusiness favRecipeBusiness;


	public String showFav() {
		FacesContext facesContext = FacesContext.getCurrentInstance();
		HttpSession session = (HttpSession) facesContext.getExternalContext().getSession(false);
		connectedUser = (User) session.getAttribute("connectedUser");
		connectedUserRecipes = favRecipeBusiness.favoriteRecipesByUser(connectedUser);
		return "/recipebyuser.xhtml?faces-redirection=true";	
	}
	public List<Recipe> getAll(){
		List<Recipe> recipes = null;
		recipes = recipeBusiness.getAll();
		return recipes;
	}
	public Set<Recipe> getAllRecipes(){
		Set<Recipe> recipes = null;
		recipes = recipeBusiness.getAllRecipes();
		return recipes;
	}
	public Recipe getById(int id) {
		Recipe recipe = new Recipe();
		int recipeId = recipe.getId();
		return recipeBusiness.getById(recipeId);
	}
	public String redirectToRecipe(Recipe recipe) {
		this.recipe = recipe;
		return "/recipe.xhtml?faces-redirection=true";
	}
	public List<Recipe> getAllPremiumRecipes(){
		List<Recipe> recipes = null;
		recipes = recipeBusiness.getAllPremiumRecipes();
		return recipes;
	}
	public List<Recipe> getAllFreeRecipes(){
		List<Recipe> recipes = null;
		recipes = recipeBusiness.getAllFreeRecipes();
		return recipes;
	}
	public void add() {
		favRecipeBusiness.add(recipe.getId(), connectedUser.getId());
	}

	public Set<Recipe> getConnectedUserRecipes(){
		return connectedUserRecipes;
	}

	public void setConnectedUserRecipes(Set<Recipe> connectedUserRecipes) {
		this.connectedUserRecipes = connectedUserRecipes;
	}

	public User getConnectedUser() {
		return connectedUser;
	}

	public void setConnectedUser(User connectedUser) {
		this.connectedUser = connectedUser;
	}

	public Recipe getRecipe() {
		return recipe;
	}

	public void setRecipe(Recipe recipe) {
		this.recipe = recipe;
	}
	public FavoriteRecipe getFavRecipe() {
		return favRecipe;
	}
	public void setFavRecipe(FavoriteRecipe favRecipe) {
		this.favRecipe = favRecipe;
	}


}

MPMG-Web/src/main/java/fr/eql/ai110/mpmg/controller/UserManagedBean.java
package fr.eql.ai110.mpmg.controller;

import java.io.Serializable;

import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

import fr.eql.ai110.mpmg.entity.FavoriteRecipe;
import fr.eql.ai110.mpmg.entity.Recipe;
import fr.eql.ai110.mpmg.entity.User;
import fr.eql.ai110.mpmg.ibusiness.AccountIBusiness;
import fr.eql.ai110.mpmg.ibusiness.FavoriteRecipeIBusiness;

@ManagedBean(name="mbUser")
@SessionScoped
public class UserManagedBean implements Serializable {

	private static final long serialVersionUID = 1L;
	
	private User user;
	private Recipe recipe;
	private FavoriteRecipe favRecipe;
	
	@EJB
	private AccountIBusiness accountBusiness;
	
	@EJB
	private FavoriteRecipeIBusiness favBusiness;
	
	
	public User update() {
		return accountBusiness.update(user);
	}
	public void add() {
		favBusiness.add(recipe.getId(), user.getId());
	}


	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}
	public Recipe getRecipe() {
		return recipe;
	}
	public void setRecipe(Recipe recipe) {
		this.recipe = recipe;
	}
	public FavoriteRecipe getFavRecipe() {
		return favRecipe;
	}
	public void setFavRecipe(FavoriteRecipe favRecipe) {
		this.favRecipe = favRecipe;
	}
	
	
	
	

}

MPMG-Web/src/main/webapp/arch.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui" xmlns:b="http://bootsfaces.net/ui"
	xmlns:c="http://java.sun.com/jsp/jstl/core">

<h:head>
	<ui:insert name="head"></ui:insert>
	<h:outputStylesheet library="css" name="style.css" />
</h:head>
<h:body>
	<div
		class="mpmg-header mpmg-flex-justify-content mpmg-flex-align-items">
		<h1>Mon pain et mes gâteaux</h1>
	</div>
	<b:form>
		<b:navBar class="navbarLinks"
			brand="#{mbLogin.user.name} #{mbLogin.user.surname}">
			<b:navbarLinks>
				<b:navLink value="Accueil" icon-awesome="home" href="index.xhtml" />
				<b:dropMenu value="Recettes">
				<b:dropMenu value="Recettes accès libre" >
				<c:forEach var="recipe" items="#{mbRecipe.allFreeRecipes}">
						<b:navCommandLink value="#{recipe.title}"
							action="#{mbRecipe.redirectToRecipe(recipe)}" />
					</c:forEach>
				</b:dropMenu>
				<b:dropMenu value="Recettes premium" >
				<c:forEach var="recipe" items="#{mbRecipe.allPremiumRecipes}">
						<b:navCommandLink value="#{recipe.title}"
							action="#{mbRecipe.redirectToRecipe(recipe)}" />
					</c:forEach>
				</b:dropMenu>
				</b:dropMenu>
				<b:navLink value="Forum" icon-awesome="weixin" href="test.xhtml"
					rendered="#{mbLogin.user.isMember}" />
				<b:navLink value="Mon espace" icon-awesome="user"
					href="useraccount.xhtml" rendered="#{mbLogin.isConnected()}" />
				<b:navCommandLink value="Mes recettes"
					action="#{mbRecipe.showFav()}" icon-awesome="cutlery"
					rendered="#{mbLogin.isConnected()}" />
				<b:navLink value="Connexion" icon-awesome="key" href="login.xhtml"
					rendered="#{!mbLogin.isConnected()}" />
				<b:navCommandLink value="Déconnexion" icon-awesome="" 
					rendered="#{mbLogin.isConnected()}"
					action="#{mbLogin.disconnect()}" />
				<b:navLink value="Nouveau compte" icon-awesome="home"
					href="create.xhtml" rendered="#{!mbLogin.hasAccount()}" />
			</b:navbarLinks>
		</b:navBar>
	</b:form>
	<b:container>
		<b:row>
			<b:column style-class="mpmg-content">
				<ui:insert name="content"></ui:insert>
			</b:column>
		</b:row>

	</b:container>
	<div
		class="mpmg-footer mpmg-flex-justify-content mpmg-flex-align-items">
		<h2>MPMG - 2022</h2>
	</div>
</h:body>
</html>

MPMG-Web/src/main/webapp/create.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui" xmlns:b="http://bootsfaces.net/ui">

<ui:composition template="/arch.xhtml">
	<ui:define name="head">
		<title>Creation</title>
		<f:metadata>
			<f:event listener="#{mbLogin.disconnect()}" type="preRenderView"></f:event>
		</f:metadata>
	</ui:define>
	<ui:define name="content">
		<b:form id="loginForm">
			<b:panel
				style-class="col-sm-offset-1 col-md-offset-2 col-xs-12 col-sm-10 col-md-8">
					<b:row>
						<b:column
							style-class="hidden-xs mpmg-top-1rem col-sm-offset-1 col-sm-2 col-md-2">
							<h:outputText value="Name" />
						</b:column>
						<b:column
							style-class="hidden-sm hidden-md hidden-lg col-xs-offset-1 col-xs-10">
							<h:outputText value="Name" />
						</b:column>
						<b:column
							style-class="col-xs-offset-1 col-sm-offset-0 col-xs-10 col-sm-8 col-md-8">
							<b:inputText id="inpName"
								placeholder="Veuillez entrer votre Prénom"
								value="#{mbLogin.name}">
								<f:facet name="prepend">
									<b:icon name="user" />
								</f:facet>
							</b:inputText>
						</b:column>
					</b:row>
					<b:row>
						<b:column
							style-class="hidden-xs mpmg-top-1rem col-sm-offset-1 col-sm-2 col-md-2">
							<h:outputText value="Surname" />
						</b:column>
						<b:column
							style-class="hidden-sm hidden-md hidden-lg col-xs-offset-1 col-xs-10">
							<h:outputText value="Surname" />
						</b:column>
						<b:column
							style-class="col-xs-offset-1 col-sm-offset-0 col-xs-10 col-sm-8 col-md-8">
							<b:inputText id="inpSurname"
								placeholder="Veuillez entrer votre Nom"
								value="#{mbLogin.surname}">
								<f:facet name="prepend">
									<b:icon name="user" />
								</f:facet>
							</b:inputText>
						</b:column>
					</b:row>
					<b:row>
						<b:column
							style-class="hidden-xs mpmg-top-1rem col-sm-offset-1 col-sm-2 col-md-2">
							<h:outputText value="Email" />
						</b:column>
						<b:column
							style-class="hidden-sm hidden-md hidden-lg col-xs-offset-1 col-xs-10">
							<h:outputText value="Email" />
						</b:column>
						<b:column
							style-class="col-xs-offset-1 col-sm-offset-0 col-xs-10 col-sm-8 col-md-8">
							<b:inputText id="inpEmail"
								placeholder="Veuillez renseigner votre adresse email Monemail@example.com"
								value="#{mbLogin.email}">
								<f:facet name="prepend">
									<b:icon name="envelope" />
								</f:facet>
							</b:inputText>
						</b:column>
					</b:row>
					<b:row>
				</b:row>
				<b:row>
					<b:column
						style-class="hidden-xs mpmg-top-1rem col-sm-offset-1 col-sm-2 col-md-2">
						<h:outputText value="Identifiant" />
					</b:column>
					<b:column
						style-class="hidden-sm hidden-md hidden-lg col-xs-offset-1 col-xs-10">
						<h:outputText value="Identifiant" />
					</b:column>
					<b:column
						style-class="col-xs-offset-1 col-sm-offset-0 col-xs-10 col-sm-8 col-md-8">
						<b:inputText id="inpLogin"
							placeholder="Veuillez entrer un identifiant"
							value="#{mbLogin.login}">
							<f:facet name="prepend">
								<b:icon name="home" />
							</f:facet>
						</b:inputText>
					</b:column>
				</b:row>
				<b:row>
					<b:column
						style-class="hidden-xs mpmg-top-1rem col-sm-offset-1 col-sm-2 col-md-2">
						<h:outputText value="Mot de passe" />
					</b:column>
					<b:column
						style-class="hidden-sm hidden-md hidden-lg col-xs-offset-1 col-xs-10">
						<h:outputText value="Mot de passe" />
					</b:column>
					<b:column
						style-class="col-xs-offset-1 col-sm-offset-0 col-xs-10 col-sm-8 col-md-8">
						<b:inputSecret id="inpPassword"
							placeholder="Veuillez entrer un mot de passe"
							value="#{mbLogin.password}">
							<f:facet name="prepend">
								<b:iconAwesome name="key" />
							</f:facet>
						</b:inputSecret>
					</b:column>
				</b:row>
				<b:row>
					<b:column>
						<b:message for="inpPassword" />
						<b:message for="inpEmail" />
					</b:column>
				</b:row>
				<b:row>
					<b:column
						style-class="mpmg-padding-1rem col-xs-offset-1 col-sm-offset-1 col-xs-10 col-sm-10 col-md-4">
						<b:commandButton style-class="mpmg-width-100" value="Création"
							action="#{mbLogin.create()}" />
					</b:column>
				</b:row>
			</b:panel>
		</b:form>
	</ui:define>
</ui:composition>
</html>

MPMG-Web/src/main/webapp/index.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui" xmlns:b="http://bootsfaces.net/ui">

<ui:composition template="/arch.xhtml">
	<ui:define name="head">
		<title>Accueil</title>
	</ui:define>
	<ui:define name="content">
	<div class="titrecarousel">
	<h1>Recettes populaires du moment</h1>
	</div>
	<br/>
	<b:container class="parentcontainer">
<b:carousel class="carouselcontainer" style="width:400px" interval="5000" >
 <b:carouselItem >
  <h:graphicImage library="pictures" name="brioche.jpg" alt="Brioche" style="width: 800px; height: 600px" />
  <b:carouselCaption>
   <h2 style="color : rgb(255,215,0); font-weight: bolder;">Notre brioche</h2>
    <p style="color : rgb(255,215,0); font-weight: bolder;">Une merveilleuse gourmandise 
    à faire tout seul ou avec les enfants.</p>
  </b:carouselCaption>
 </b:carouselItem>
 <b:carouselItem>
  <h:graphicImage library="pictures" name="kouignamann.jpg" alt="Tourte de seigle" style="width: 800px; height: 600px" />
  <b:carouselCaption>
   <h2 style="color : rgb(255,215,0); font-weight: bolder;">Kouign amann</h2>
  </b:carouselCaption>
 </b:carouselItem>
 <b:carouselItem>
  <h:graphicImage library="pictures" name="fraisier.jpg" alt="Fraisier" style="width: 800px; height: 600px" />
  <b:carouselCaption>
   <h2 style="color : rgb(255,215,0); font-weight: bolder;">Fraisier crème au beurre</h2>
  </b:carouselCaption>
 </b:carouselItem>
 <b:carouselItem>
  <h:graphicImage library="pictures" name="canele.jpg" alt="Canelé" style="width: 800px; height: 600px" />
  <b:carouselCaption>
   <h2 style="color : rgb(255,215,0); font-weight: bolder;">Canelés de Bordeaux</h2>
   <p style="color : rgb(255,215,0); font-weight: bold;">Recette authentique par notre chef Bruno Albouze</p>
  </b:carouselCaption>
 </b:carouselItem>
 <b:carouselItem>
  <h:graphicImage library="pictures" name="fondant.jpg" alt="Fondant" style="width: 800px; height: 600px" />
   <b:carouselCaption>
   <h2 style="color : rgb(255,215,0); font-weight: bolder;">Fondant au chocolat</h2>
  </b:carouselCaption>
 </b:carouselItem>
</b:carousel>
<p class="descsite">Mon pain et mes gâteaux est un espace de partage et d'apprentissage. 
Nous avons des recettes accessibles à tout le monde et des recettes premium qui sont payantes. 
Nous avons décidé de les rendre payante car il y a un chef qui s'investit, en plus de vous donner 
les meilleures recettes vous donne aussi des astuces et des conseils pour bien réussir la recette. 
C'est l’équivalent d’une masterclass  condensée.</p>
</b:container>
	</ui:define>
</ui:composition>
</html>

MPMG-Web/src/main/webapp/login.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui" xmlns:b="http://bootsfaces.net/ui">

<ui:composition template="/arch.xhtml">
	<ui:define name="head">
		<title>Identification</title>
		<f:metadata>
			<f:event listener="#{mbLogin.disconnect()}" type="preRenderView"></f:event>
		</f:metadata>
	</ui:define>
	<ui:define name="content">
		<b:form id="loginForm">
			<b:panel
				style-class="col-sm-offset-1 col-md-offset-2 col-xs-12 col-sm-10 col-md-8">
				<b:row>
					<b:column
						style-class="hidden-xs mpmg-top-1rem col-sm-offset-1 col-sm-2 col-md-2">
						<h:outputText value="Identifiant" />
					</b:column>
					<b:column
						style-class="hidden-sm hidden-md hidden-lg col-xs-offset-1 col-xs-10">
						<h:outputText value="Identifiant" />
					</b:column>
					<b:column
						style-class="col-xs-offset-1 col-sm-offset-0 col-xs-10 col-sm-8 col-md-8">
						<b:inputText id="inpLogin"
							placeholder="Veuillez entrer un identifiant"
							autocomplete="false"
							value="#{mbLogin.login}">
							<f:facet name="prepend">
								<b:icon name="user" />
							</f:facet>
						</b:inputText>
					</b:column>
				</b:row>
				<b:row>
					<b:column
						style-class="hidden-xs mpmg-top-1rem col-sm-offset-1 col-sm-2 col-md-2">
						<h:outputText value="Mot de passe" />
					</b:column>
					<b:column
						style-class="hidden-sm hidden-md hidden-lg col-xs-offset-1 col-xs-10">
						<h:outputText value="Mot de passe" />
					</b:column>
					<b:column
						style-class="col-xs-offset-1 col-sm-offset-0 col-xs-10 col-sm-8 col-md-8">
						<b:inputSecret id="inpPassword"
							placeholder="Veuillez entrer un mot de passe"
							autocomplete="false"
							value="#{mbLogin.password}">
							<f:facet name="prepend">
								<b:iconAwesome name="key" />
							</f:facet>
						</b:inputSecret>
					</b:column>
				</b:row>
				<b:row>
					<b:column>
						<b:message for="inpPassword" />
						<b:message for="inpLogin" />
					</b:column>
				</b:row>
				<b:row>
					<b:column
						style-class="mpmg-padding-1rem col-xs-offset-1 col-sm-offset-1 col-xs-10 col-sm-10 col-md-4">
						<b:commandButton style-class="mpmg-width-100" value="Connexion"
							action="#{mbLogin.connect()}" />
					</b:column>
					<b:column
						style-class="mpmg-padding-1rem col-xs-offset-1 col-sm-offset-1 col-md-offset-2 col-xs-10 col-sm-10 col-md-4">
						<b:commandButton style-class="mpmg-width-100"
							value="Mot de Passe oublié" action="#{mbLogin.connect()}" />
					</b:column>
				</b:row>
			</b:panel>
		</b:form>
	</ui:define>
</ui:composition>
</html>

MPMG-Web/src/main/webapp/recipe.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui" 
	xmlns:b="http://bootsfaces.net/ui"
	xmlns:c="http://java.sun.com/jsp/jstl/core">

<ui:composition template="/arch.xhtml">
	<ui:define name="content">
		 <h:form>
            <b:panel title="#{mbRecipe.recipe.title}" collapsed="false">
	            <h:graphicImage value="./resources/pictures/#{mbRecipe.recipe.picture}"/><br/>
	            <h:outputLabel value="Difficulté : " /><h:outputText value=" #{mbRecipe.recipe.difficulty}" /><br/>
	            <h:outputLabel value="Temps de préparation : " /><h:outputText value="#{mbRecipe.recipe.prepTime}" /><br/>
	            <h:outputLabel value="Temps de cuisson : " /><h:outputText value="#{mbRecipe.recipe.cookingTime}" /><br/>
            </b:panel>
        </h:form>
	</ui:define>
</ui:composition>
</html>

MPMG-Web/src/main/webapp/test.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui" 
	xmlns:b="http://bootsfaces.net/ui"
	xmlns:c="http://java.sun.com/jsp/jstl/core">

<ui:composition template="/arch.xhtml">
	<ui:define name="head">
		<title>Toutes les recettes</title>
	</ui:define>
	
	<ui:define class="toutesMesRecettes" name="content">
	<h1>Toutes les recettes</h1>
		 <h:form>
          <c:forEach var="recipe" items="#{mbRecipe.all}">
            <b:column title="#{recipe.title}" value="#{recipe.title}" collapsed="true">
            <h:graphicImage value="./resources/pictures/#{recipe.picture}"/><br/>
            <h:outputLabel value="#{recipe.title}" /><br/>
            <h:outputLabel value="#{recipe.description}" /><br/>
            <h:outputLabel value="#{recipe.prepTime}" /><br/>
            </b:column>
          </c:forEach>
        </h:form>
	</ui:define>
</ui:composition>


</html>